#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 22 17:05:38 +07 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_lstm_layer_behav -key {Behavioral:tb_lstm_layer:Functional:tb_lstm_layer} -tclbatch tb_lstm_layer.tcl -log simulate.log"
xsim tb_lstm_layer_behav -key {Behavioral:tb_lstm_layer:Functional:tb_lstm_layer} -tclbatch tb_lstm_layer.tcl -log simulate.log

